### ISSUE TITLE
namespace changes in at_contacts

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_libraries#101]

**Comment by murali-shris** [comment]
* changes for namespace for keys created in at_contacts library

**Comment by ksanty** [comment]
@murali-shris can you please add a [label(s)](https://github.com/atsign-company/labels/labels) to this so we can better track status?  TY

**Comment by DivyaYadavareddy** [comment]
Added namespace changes in at_contact library and published it to pub.dev with version (at_contact: ^2.0.3)
