### ISSUE TITLE
-- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_libraries#120]
**Describe the solution you'd like**

Per the guidance from [dart-lang/lints](https://github.com/dart-lang/lints#migrating-from-packagepedantic):

in each `pubspec.yaml`:

```diff
-  pedantic: ^1.11.0
+  lints: ^1.0.1
```

and in each `analysis_options.yaml`:

```diff
-include: package:pedantic/analysis_options.yaml
+include: package:lints/recommended.yaml
```

**Comment by aniketh-varma** [comment]
Hi, can I work on this issue?

**Comment by ksanty** [comment]
Just added you to the issue @aniketh-varma.
