### ISSUE TITLE
decide whether or not to add "packages" subdirectory for libraries published to pub.dev

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/at_libraries#123]
**Is your feature request related to a problem? Please describe.**
The current directory structure creates bad links on pub.dev for Example content.
For example, clicking on the [example/at_server_status_example.dart](https://github.com/atsign-foundation/at_libraries/blob/master/example/at_server_status_example.dart) link on the [at_server_status](https://pub.dev/packages/at_server_status/example) Example tab returns a 404 response because it references the root of the at_libraries repo and not that of the package itself.

**Describe the solution you'd like**
Rumor has it that adding a "packages" subdirectory from root resolves this for pub.dev. We need to test and validate this is true and then add the subdirectory if it works.

**Describe alternatives you've considered**
The other option would be to create separate repos for each package that we want to publish to pub.dev

**Additional context**

**Comment by cpswan** [comment]
After further discussion with @XavierChanth and others I'm not sure that we should refactor existing packages. We just need to ensure that we have correct `repository:` tags defined in pubspec.yaml to prevent 404s.

We can however start using the packages convention for future pubdev repos by putting it in the archetype-pubdev template.
