### ISSUE TITLE
Race condition in AtLookupImpl._process

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_libraries#140]
**Describe the bug**
* `AtLookupImpl._process()` does a few things - authenticates if necessary, sends a command, reads a response
* The intent is that all of that should happen as a single atomic group
* However there is no mutex guaranteeing that. As a result, for example, a caller can receive the response from a different request.

**To Reproduce**
* Have one piece of code for atSign_1 which is in a loop which calls AtClient.put() twice in rapid succession with two different keys, key1 and key2, which are sharedWith atSign_2, then waits for a second before doing it again
* Have another piece of code for atSign_2 which has subscribed to notifications, and in the notification callback calls AtClient.get() for whichever key (key1 or key2)

**Expected behaviour**
* No race condition

Fixed by #139

**Comment by murali-shris** [comment]
import 'dart:io';

import 'package:at_client/at_client.dart';
import 'package:at_client/src/manager/at_client_manager.dart';
import 'package:at_utils/at_logger.dart';

import 'dart:convert';
import 'dart:typed_data';
import 'package:crypto/crypto.dart';

void main() async {
  AtSignLogger.root_level = 'finest';
  final atSign = 'alice';
  var atClientManager = await AtClientManager.getInstance()
      .setCurrentAtSign(atSign, 'wavi', _getPreference());
  try {
    while (true) {
      print('sync in progress');
      var a = await atClientManager.syncService.isInSync();
      print('Are we waiting ?' + a.toString());
      sleep(Duration(seconds: 5));
    }
  } on Exception catch(e, trace) {
    print(e);
    print(trace);
  }
  print('OK Ready');
}

AtClientPreference _getPreference() {
  var preference = AtClientPreference();
  preference.hiveStoragePath = '/home/murali/work/2020/hive/client';
  preference.commitLogPath = '/home/murali/work/2020/hive/client/commit';
  preference.isLocalStoreRequired = true;
  preference.privateKey =
  '<your_private_key_here>';
  preference.rootDomain = 'root.atsign.org';
  var hashFile = _getShaForAtSign('@zathura97tall');
  preference.keyStoreSecret = _getKeyStoreSecret(
      '/home/murali/work/2020/hive/client/' + hashFile + '.hash');
  return preference;

}

List<int> _getKeyStoreSecret(String filePath) {
var hiveSecretString = File(filePath).readAsStringSync();
var secretAsUint8List = Uint8List.fromList(hiveSecretString.codeUnits);
return secretAsUint8List;
}

String _getShaForAtSign(String atsign) {
var bytes = utf8.encode(atsign);
return sha256.convert(bytes).toString();
}

**Comment by murali-shris** [comment]
@gkc above code doesn't complete successfully with trunk branch of at_client pointing to your branch of at_lookup quickFixAtLookupRaceCondition
In _processSyncRequests()
 _syncInProgress = true;
  final serverCommitId = await _getServerCommitId();// stats:3 request probably is sent(unable to confirm since server has only INFO logs). The response is not received and _syncInProgress never gets set to false.

**Comment by murali-shris** [comment]
> @gkc above code doesn't complete successfully with trunk branch of at_client pointing to your branch of at_lookup quickFixAtLookupRaceCondition In _processSyncRequests() _syncInProgress = true; final serverCommitId = await _getServerCommitId();// stats:3 request probably is sent(unable to confirm since server has only INFO logs). The response is not received and _syncInProgress never gets set to false.

@gkc after running the tests multiple times I figured that issue happens even without your code changes..Issue requires a fix in SyncServiceImpl.

**Comment by gkc** [comment]
Yep it's unrelated

**Comment by gkc** [comment]
Closing - fixed by #139 and new at_lookup package 3.0.8 published
