### ISSUE TITLE
AtLookup fails on iPad

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_libraries#167]
**Describe the bug**
During onboarding flow, AtLookup throws error

**To Reproduce**
1. First I installed both atmosphere-pro and wavi on iPad
2. Then I tried to onboard an atsign
3. Onboarding flow failed with CERTIFICATE issue

**Expected behavior**
Onboarding flow should work as on any other device

**Screenshots**
![0A0A4651-6C6B-4AB0-899F-CD6C9AD8A2B6](https://user-images.githubusercontent.com/12222326/167639710-b8602bd3-4a18-4271-9b15-8480a26c0eda.png)

**Smartphone (please complete the following information):**
Device: iPad mini
OS version: 9.3.5

**Were you using an @‎application when the bug was found?**
  - atmosphere-pro
  - wavi

**Additional context**
Captured some more information via the dev tools and console.

**The network calls:**
<img width="1502" alt="Screenshot 2022-05-10 at 6 32 10 PM" src="https://user-images.githubusercontent.com/12222326/167640151-aa520647-4063-407c-8777-6e9b1b5bf22f.png">

<img width="1502" alt="Screenshot 2022-05-10 at 6 31 43 PM" src="https://user-images.githubusercontent.com/12222326/167640213-3e4e2c51-8fdb-4ddb-8961-60f6e764dfa0.png">

**App log:**
<img width="1506" alt="Screenshot 2022-05-10 at 6 44 36 PM" src="https://user-images.githubusercontent.com/12222326/167640322-80b516ae-6bef-4c4f-b5e2-c06d45d5cbaa.png">

**Checking the secondary:**
<img width="853" alt="Screenshot 2022-05-10 at 6 45 17 PM" src="https://user-images.githubusercontent.com/12222326/167640455-76ba2752-f4d3-4d85-8a8e-12b786fdf55d.png">
<img width="1024" alt="Screenshot 2022-05-10 at 6 45 30 PM" src="https://user-images.githubusercontent.com/12222326/167640521-da577c37-d77b-4412-8bee-92f54b4e0943.png">
<img width="1501" alt="Screenshot 2022-05-10 at 6 45 43 PM" src="https://user-images.githubusercontent.com/12222326/167640592-45c09677-ceb6-452b-b07d-3e34dd6f4445.png">

**Comment by sarika01** [comment]
The same atsign works fine on mobile and desktop versions.

**Comment by gkc** [comment]
9.3.5 operating system is very old, does not have the required cert in its root certs list

I presume the iPad mini is 1st generation, for which 9.3.5 is the last supported version of iOS

See here: https://discussions.apple.com/thread/253219776?answerId=253219776021#253219776021

which says to try this: 
> Go to https://letsencrypt.org/certs/isrgrootx1.pem in Safari on your iPad. It should prompt you to install the certificate.

**Comment by sarika01** [comment]
On installing the certificate, the issue was resolved.
