### ISSUE TITLE
Onboard atSigns easily in headless systems

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_libraries#222]
## **Background:**

I was writing documentation for sshnp on the dev site, then I realized the first step was to prepare two atSigns and their `.atKeys` files.

Getting the atSigns is the easy part, but for somebody who wants to use something like ssh no ports and want nothing to do with our apps or ecosystem, it may be hard for them to onboard their atSigns and generate the `.atKeys` files.

## **Problem:**

For headless tools/systems like sshnp, there should be an easy way to generate the `.atKeys` files without having to write dart code or download our apps.

## **Proposal:**

Using `at_onboarding_cli`, create a binary called "onboard."

```sh
./onboard <email> <atSign> // arguments can be figured out more in detail later
```

This binary could be released with the `sshnp` binaries, or just remain as a release or file in `at_libraries/at_onboarding_cli`

## **Random Ideas:**

We could also have a **register binary** for skipping the atSign purchasing process altogether; the goal is for the person using sshnp to focus on using sshnp and not the atSign portion. (But if we want them to be involved in our atPlatform ecosystem, I could see why this is not an angle we want to take; but I believe we should make it easy for devs to use sshnp to avoid scaring them away, even if it means they don't know what an atSign really is)

The goal of having the register binary would be to steer them away from the complexities of what an "atSign" is.  After all, the developers primary concern is to ssh without open ports and things would ideally just *work*.

**Comment by JeremyTubongbanua** [comment]
I've started working a little bit.

**Comment by tinashe404** [comment]
@JeremyTubongbanua the requirement for the cram key update we spoke about can be done by Srie Teja.

**Comment by srieteja** [comment]
PR reg this task is awaiting review. This issue will be closed after a newer version of at_onboarding_cli has been released.
