### ISSUE TITLE
at_lookup 3.0.30 printing out signature to console during PKAM auth

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_libraries#228]
**Describe the bug**
The latest version of at_lookup includes a line in `at_lookup_impl.dart` that prints outs the PKAM challenge signature to the console

**To Reproduce**
1. First I wrote a small onboarding cli app
2. Then I saw the signature printed to screen!
3. And then investigated why
4.  Trunk does not have this bug so its been cleared up but the pub.dev lib has not been updated.
5. Needs to be

**Expected behavior**
No prints in production code 

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Dart/Flutter

**Additional context**

line 381 of  `at_lookup_impl.dart`
`print(signature);`

**Comment by purnimavenkatasubbu** [comment]
at_lookup: ^3.0.31 is published with the change.

**Comment by cconstab** [comment]
Thank you!

**Comment by cconstab** [comment]
Confirmed thanks
