### ISSUE TITLE
Atsign auto-activation takes a while and code may progress too quickly

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_libraries#232]
## Summary
Now that auto activation is a feature in the registrar, sometimes activating the atSign will take a while. Code may go straight to `onboard()` with the cram key however the secondary address is not initialized. This may become a problem if CLI code tries to onboard too quickly.

## Steps to reproduce

```
1. Activate an unactivated atSign via the web API
2. Web API will give you a cram key, but the secondary address is still null.
3. Try to onboard immediately upon receiving the cram key
4. You will receive a secondary not found because the atSign's secondary was not initialized quickly enough
```

## Hotfix

Simply pause your code until the secondary address can be found.
```dart
/// Hot fix in case activating the atSign takes too long (if the person does not press the orange "Activate" button on their atSign, then the secondary was not initialized just yet. Just run this method with async/await and it will pause your code until the secondary is successfully initialized.)
  Future<void> runUntilSecondaryExists(String rootUrl, String atSign, {timeoutIterations = 10000000}) async {
  List<String> s = rootUrl.split(':');
    String rootDomain = s[0];
    int rootPort = int.parse(s[1]);
    late SecondaryAddress sAddress;
    bool exists = false;
    int timeout = timeoutIterations;
    int count = 0;
    do {
      count++;
      try {
        sAddress = await CacheableSecondaryAddressFinder(rootDomain, rootPort).findSecondary(atSign);
        exists = true;
      } catch (e) {
        // ignore
      }

    } while(!exists && count < timeout); 
    if(sAddress.host.length > 2) {
      print('Secondary address found! ${sAddress.host}:${sAddress.port} | Iterations: $count/$timeout');
    } else {
      print('Secondary address not found after $count/$timeout iterations');
    }
    throw Exception('Secondary address not found after $count/$timeout iterations');
  }
```

### Hotfix use example:

```dart
// 1. 
// get the cram key from via the web api 
// (will actually give a non-null valid cramkey despite secondaryUrl not addressable).
String? cram = await apiUtil.authenticateAtSignValidate(atSign, otp);

// 2. 
// pause code until secondaryUrl is addressable
await apiUtil.runUntilSecondaryExists(rootUrl, atSign);

// 3. 
// onboard with the cram key (this function ultimately looks for secondaryUrl.. 
// if the pause code above were to be excluded, then it would immediately jump 
// into this code block and look for a non-existent secondaryUrl).
bool onboarded = await onboard(atSign, rootUrl, cram);
```

**Comment by JeremyTubongbanua** [comment]
@tinashe404 Feel free to give your thoughts
Also feel free to change the repo if it's in the wrong place and/or add more assignees. Thank you

**Comment by srieteja** [comment]
Are we planning to implement the registrarV3(the one with activation keys)? This issue only pops up on v3.

**Comment by tinashe404** [comment]
@athandle ... please confirm..

**Comment by athandle** [comment]
@srieteja  can you please confirm which API(end points) you are using?

**Comment by srieteja** [comment]
@athandle at the moment I'm using all v2 end-points(get-free-atsign, register-person, validate-person). The question is should I also provide an implementation for v3 ones too?

**Comment by athandle** [comment]
@srieteja you mentioned issue is with v3. Can you please clarify that.

We have to wait till secondary is started that I think you are aware of that is part of all version of APIs

Yes we have to use v3 but there are minor changes that I have to communicate and I am documenting 
https://docs.google.com/document/d/1X9dbqeB5TE4XIlYzNdenGK1iNAseMs-HdllLF8XPBl8/edit?usp=sharing

**Comment by srieteja** [comment]
I have majorly faced this issue with v3 atsigns so I assumed it is only specific to v3. If it's present in v2 and v3, I guess this is something we need to solve this issue for all secondaries.

**Comment by athandle** [comment]
@srieteja  behind the scene APIs are not changed just name and response structure. Secondary creation process is same behind the scene.
Do you have wait logic till secondary start in your code or not? If not then check on boarding widget code or check with Sachin to help

**Comment by srieteja** [comment]
In at_java, I put a wait logic for onboarding. I'll do the same for dart too.

**Comment by ksanty** [comment]
@JeremyTubongbanua can you add some labels to this issue?  TY!

**Comment by JeremyTubongbanua** [comment]
Hey @ksanty , sorry I don't know what labels you want me to add...

**Comment by ksanty** [comment]
> Hey @ksanty , sorry I don't know what labels you want me to add...

Is this a bug?  Enhancement?  Just a lil context.  I can create a new label if we don't have one that suits @JeremyTubongbanua

**Comment by JeremyTubongbanua** [comment]
> > Hey @ksanty , sorry I don't know what labels you want me to add...
> 
> Is this a bug? Enhancement? Just a lil context. I can create a new label if we don't have one that suits @JeremyTubongbanua

Hmm I would consider this a bug because it would cause errors on my end.

Thanks :)

**Comment by srieteja** [comment]
The fix is ready to be pushed into trunk as part of the PR that has been linked. Minor problem with failing tests which needs to be resolved before merging.
