### ISSUE TITLE
Secure element: Integrate the at_signing work into the at_chops package

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_libraries#246]
### Is your feature request related to a problem? Please describe.

See https://github.com/atsign-foundation/at_client_sdk/issues/756 and https://github.com/atsign-foundation/at_libraries/issues/235

### Describe the solution you'd like

Incorporate the signing library into the overall at_chops library

**Comment by gkc** [comment]
@srieteja : Murali has got the at_chops work to the point that it should be possible to do this integration during this sprint

**Comment by srieteja** [comment]
Sure, @gkc. I've wrapped up most of my current tasks. Will take this up next.

**Comment by srieteja** [comment]
Spent most of my time on the client-side sync tests in the last sprint and could not work on this. Will make sure to take this up in the coming sprint.

**Comment by srieteja** [comment]
Spent time on analysis and initial implementation. Will continue the work into PR54.

**Comment by srieteja** [comment]
A majority of the work is done. There is a basic existing implementation already present, so have to spend additional time to resolve the design conflicts. Will be carrying it into the next sprint.

**Comment by murali-shris** [comment]
Made changes to add public key as optional param to verify method
https://github.com/atsign-foundation/at_libraries/commit/2aad296c4d48d4abf66fffd7985008e471a8c78d
* unit tests pending
* publish at_chops

**Comment by murali-shris** [comment]
at_commons v3.0.39
at_chops v1.0.1 published
