### ISSUE TITLE
Register CLI - Issues

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_libraries#263]
Below is a list of the issues and enhancements that have been identified while testing the most recent version of the Register CLI.

### **Issues**
**Bugs**
- [x] While running the tool from the code base, when my atSign was activating I saw multiple lines of "Connecting to secondary...." on attempt resulted in 14 lines of this and another attempt resulted in 100s of lines as this went on for a few minutes until I terminated it. 
- [x] If someone already has 10 free atSigns registered to their email and they try to get another one using the tool, it is displaying the correct message however it is then proceeding to throw an unhandled exception. Please proposed steps for handling this on page 2 of the [wording doc ](https://docs.google.com/document/d/1bM6z2Qu0XzFc-K5RYmFXqo7GE-3PYDlJ7MDIbR5hM-M/edit#) [DONE]
- [x] If someone runs the tool with an option that doesn't exist, eg -r, we are getting an unhandled exception. This should be handled in the same way as when someone runs the tool without entering any options. [DONE]
- [x] If someone runs the tool with the correct -e option but no email address, we are getting an unhandled exception. This should be handled in the same way as when someone runs the tool without enter any options. [DONE]
- [x] If someone runs the tool with the correct -e option but the email address is not in the correct format eg hhhhhhhhh, we are getting the correct message saying unable to run , you have entered an invalid email etc but then the tool proceeds to get an atSign and attempts to send the verification code to null and we get an unhandled exception. After displaying the unable to run Register Cli message, the tool should stop and prompt the person to enter their email address again [Action Required] Enter your email address: [DONE]

**Wording/Visual**
- [x] After using the tool successfully the final log displayed after letting me know where my atKeys are stored says "SEVERE|2022-12-8 10:44:12.082697|OnboardingCli}Killing current instance of at_onboarding_cli". If this is meant to signify the successful end of the process then could we replace this with something a little friendlier? SEVERE implies something has gone wrong. Maybe [Information] Your atSign Registration has been completed. 
- [x] When asked to enter my verification code, if I press enter without typing anything it says "Enter you verification code", but it should be "Enter your verification code" [DONE]
- [x] When it's activating the atSign it says "Activating you atSign: @tinashe404", but it should be "Activating your atSign: @tinashe404". This line also appears twice instead of only once.
- [x] When generating the keys it says "Generating you encryption keys and .atKeys file", but it should be "Generating your encryption keys and .atKeys file"

### **Enhancements**
- [x] Provide the Register CLI in the form of a downloadable binary. I attempted to access it using "dart pub global..." and although activation was successful, I was not able to run it. I got "Could not find an option or flag -e" after running "dart pub global at_register -e myemailaddress"
- [x] Since this tool will be used by the general public, we dont want them to have access to staging/dev and should therefore not give them the -n and --environment usage instructions [DONE]

**Comment by tinashe404** [comment]
The tool keeps hanging on "activating atSign". I waited nearly 2 minutes for the first attempt and nearly 5 minutes for the second one and it didn't progress beyond this point. 

When i logged into the dashboard, both atSigns were showing the "click to scan" button so it looks like activation did successfully start but did not finish.

![Image](https://user-images.githubusercontent.com/69275762/207476171-89696bd6-8d28-4e86-9bc8-76c4b21a5865.png)

**Comment by tinashe404** [comment]
@srieteja I tried the latest version, and still not able to activate. It hung for a while then the following logs were displayed...

![Image](https://user-images.githubusercontent.com/69275762/207741275-ef769796-bdbd-42c3-a9c7-f06048bcf01a.png)

![Image](https://user-images.githubusercontent.com/69275762/207741283-1a5e7701-c594-4da2-8281-9405bd15102f.png)

**Comment by srieteja** [comment]
@tinashe404 the above logs show that register_cli and onboarding_cli were working perfectly fine. But the secondary belonging to that atsign was not available for connection. Onboarding_cli made approx 50 attempts to connect, but the secondary was still unavailable. So, let me talk to who might know about this and find out why this is happening.

**Comment by gkc** [comment]
Attached are the [server logs](https://github.com/atsign-foundation/at_libraries/files/10237140/41wittering.logs.txt) for that secondary. The timestamps are UTC

The server finished starting up at 2022-12-14 23:58:29.276162 UTC
* `4deb50f7-94c8-5040-afcd-1235597b5d41_secondary.1.fayc2mkgcvl7@swarm0002-19.us-central1-a.c.secondaries.internal    | INFO|2022-12-14 23:58:29.276162|AtSecondaryServer|Secure Socket open for @41wittering !`

@tinashe404 if you have timestamps then this should help you identify where the problem was

**Comment by gkc** [comment]
Looking at the code
```dart
    while (secureSocket == null && _retryCount < maxRetries) {
      logger.finer('retrying connect secondary.......$_retryCount/$maxRetries');
      stdout.writeln('Connecting to secondary ...');
      try {
        secureSocket = await SecureSocket.connect(
            _secondaryAddress!.host, _secondaryAddress.port);
      } on Exception catch (e) {
        logger.finer(e);
      }
    }
```
it seems unlikely that the issue is with the CLI tool. Seems likely that the secondary was unreachable. 

Question is whether (1) the secondary was not yet running, or (2) the secondary was running but somehow this client could not establish a SecureSocket connection

@tinashe404 if you know the UTC time at which you ran the tool you may be able to answer that question

@srieteja I note that there is no delay between retrying the SecureSocket.connect
@tinashe404 do you recall how quickly in succession those "Connecting to secondary" messages were printed?

**Comment by tinashe404** [comment]
@gkc thank you for taking time to look into this. I ran the tool at around 11:58pm UTC.

The messages are printed pretty quickly. Maybe 5 or so per second.

I am going to see what the success rate is this afternoon and also look into whether that atSign's activation can be completed via an app.

**Comment by gkc** [comment]
> The messages are printed pretty quickly. Maybe 5 or so per second.

Aha ... as I suspected. I think it's just not waiting long enough for the secondary to start.

I've pushed the following changes to the srieteja-patch-6 branch:
* fix: Add a 3-second delay between attempts to look up the secondary's address
* fix: Add a 3-second delay between attempts to connect to the secondary
* fix: Add a 30-second timeout for the SecureSocket.connect call ... this should be long enough to succeed even on slow networks, but short enough that if there is some serious networking issue then we won't hang for the underlying operating system default (which is typically 3 minutes)
* chore: clean up some lint warnings

150 (3 times 50) seconds should be plenty of time for the secondary to start, although we might want to allow more.

**Comment by tinashe404** [comment]
With the changes above, I managed to successfully activate 5 atSigns. 

@srieteja Could we update "Activating your atSign" to "Activating your atSign. This may take up to 2 minutes."

**Comment by gkc** [comment]
I've just made that change @tinashe404 since I had the branch checked out

**Comment by tinashe404** [comment]
Thank you, @gkc
