### ISSUE TITLE
onboarding cli onboard method attempts cram auth if atsign is already onboarded

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_libraries#278]
### Describe the bug

Client will be able to call at_onboarding_service --> onboard multiple times.

First time onboard is called for an atsign, cram auth will be done to server and keys will be persisted to local secondary.

If client calls onboard again, with current logic cram will be unnecessarily attempted to server and would fail (cram secret will be deleted from secondary during first onboard)

Implement a method isOnboarded and check whether cram should be attempted to server.

### Steps to reproduce

* call onboard multiple times from client app

### Expected behavior

* cram should not be attempted again to server
* onboard method should return true if atsign is already onboarded
* _isAtsignOnboarded  flag must be set based on whether keys are set in local secondary. Not based on cram auth result.

**Comment by srieteja** [comment]
This issue has been fixed as part of https://github.com/atsign-foundation/at_libraries/pull/343. A check has been introduced before onboarding to see if an atsign is already activated and throwing necessary exceptions if already onboarded.
