### ISSUE TITLE
at_chops: importing keys documentation/feature

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_libraries#289]
### Is your feature request related to a problem? Please describe.

I don't know if this is a feature already, but:

I'd like to import a base 64 encoded private/public rsa key manually.

If this is a feature, I wasn't able to find any documentation/examples easily in the readme and pub.dev

### Describe the solution you'd like

Documentation on how to import keys in various ways for writing rsa decrypting/encrypting/signing/verifying code.

-  reading `.atKeys` file
- manually hard coding the base64 encoded key strings

**Comment by xavierchanth** [comment]
See at_onboarding_cli or at_onboarding_flutter/at_client_mobile for more info -- see at_talk for an example of usage.
