### ISSUE TITLE
at_chops: Change the default hashing algorithm to SHA512

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_libraries#295]
### Is your feature request related to a problem? Please describe.

md5 is prone to collisions and should not be used.

### Describe the solution you'd like

Change the algorithm to SHA512

**Comment by gkc** [comment]
Since [this commit from Feb 2023](https://github.com/atsign-foundation/at_libraries/commit/3051f7e316f561a7e2a2631cff153ddc005a49d7), attempting to use md5 to sign will throw an exception
