### ISSUE TITLE
ttr not being set on public key metadata

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_libraries#297]
### Describe the bug

at_onboarding_cli.AtOnboardingServiceImpl._activateAtsign is not setting ttr for public key, thus ttr is defaulting to null

### Expected behavior

should set a ttr of -1 (cache indefinitely) when storing the public encryption key. See [this other bug report](https://github.com/atsign-foundation/at_server/issues/1226) for the explanation of why

**Comment by gkc** [comment]
Updating to P2 as this is an annoying piece of tech debt which requires us to keep some workarounds in atServer code

**Comment by gkc** [comment]
PS I don't expect this to get done in this sprint given other priorities but would like to have it kept in Triage until someone has time to get to it

**Comment by murali-shris** [comment]
PR under review.
