### ISSUE TITLE
at_chops: integrate onboarding cli and at_chops extension with external signing logic on sim card

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_libraries#298]
### Is your feature request related to a problem? Please describe.

* Signing data using private key on sim card has been independently tested by running the AT command dart program on the raspberry pi containing the sim card
* We have to integrate onboarding cli with an at chops implementation which delegates signing logic to external program

### Describe the solution you'd like

* Extend atchops implementation and override sign method
* sign method implementation should delegate the signing logic to external program.

**Comment by murali-shris** [comment]
@cconstab @gkc @cpswan @VJag 
https://github.com/atsign-company/murali-snippets/blob/master/iotsafe/lib/src/at_chops_secure_element.dart
https://github.com/atsign-company/murali-snippets/blob/master/iotsafe/lib/src/external_signer.dart
The command line app which uses onboarding_cli with an overriden instance of at_chops (e.g at_chops_secure_element.dart) may be running on a different host and the external_signer.dart may run a different host(IoT device which has the SIM)
Any thoughts to tackle this?

**Comment by gkc** [comment]
What are the use cases in which the app and the signer might be on different hosts?

**Comment by murali-shris** [comment]
> What are the use cases in which the app and the signer might be on different hosts?

I cannot think of a use case.Since IoT devices mostly run light weight processes, I was assuming the command line app will run on a different host and communicate with the SIM on IoT device just for data signing.

**Comment by murali-shris** [comment]
@gkc @cpswan 
When an atsign is onboarded using pkam from secure element, should we generate .atKeys file in the onboarding flow (_activateAtsign method in the below file). if yes, .atKeys should contain the ecc public key, encryption key pair and self encryption key?
https://github.com/atsign-foundation/at_libraries/blob/trunk/packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart

**Comment by cpswan** [comment]
@murali-shris what would that (diminished) .atKeys file be used for?

My take on this is that the purpose of an .atKeys file is to transport exported keys from one secure enclave to another, and we accept the risks associated in doing that because of necessity.

But the keys we're using in an IoT SAFE environment aren't exportable (and don't need to be for any use cases examined so far), so there's no need for an .atKeys file.

**Comment by gkc** [comment]
Note that we store the encryption private key and the AES 'self' encryption key in 'local' storage ([at_client_mobile](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client_mobile/lib/src/at_client_service.dart#L129-L142), [at_onboarding_cli](https://github.com/atsign-foundation/at_libraries/blob/trunk/packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart#L208-L235)) and they are [never synced](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client/lib/src/util/sync_util.dart#L116-L126) to cloud secondary. For now (*), the atClient will always need to store those keys somewhere locally; an atKeys file is a reasonable choice if the client does not have 'LocalSecondary' storage. 

(*) Once [the APKAM proposal](https://github.com/atsign-foundation/at_protocol/blob/trunk/decisions/2023-01-pkam-per-app-and-device.md) has been implemented, the encryption private key and the self encryption key will be stored on the cloud secondary, but encrypted using the client's PKAM public key. At that point, a client will only need the PKAM private key so that it can (1) sign the PKAM challenge with the PKAM private key, and (2) decrypt the encryption keys using the PKAM private key

**Comment by murali-shris** [comment]
> Note that we store the encryption private key and the AES 'self' encryption key in 'local' storage ([at_client_mobile](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client_mobile/lib/src/at_client_service.dart#L129-L142), [at_onboarding_cli](https://github.com/atsign-foundation/at_libraries/blob/trunk/packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart#L208-L235)) and they are [never synced](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client/lib/src/util/sync_util.dart#L116-L126) to cloud secondary. For now (*), the atClient will always need to store those keys somewhere locally; an atKeys file is a reasonable choice if the client does not have 'LocalSecondary' storage.
> 
> (*) Once [the APKAM proposal](https://github.com/atsign-foundation/at_protocol/blob/trunk/decisions/2023-01-pkam-per-app-and-device.md) has been implemented, the encryption private key and the self encryption key will be stored on the cloud secondary, but encrypted using the client's PKAM public key. At that point, a client will only need the PKAM private key so that it can (1) sign the PKAM challenge with the PKAM private key, and (2) decrypt the encryption keys using the PKAM private key

#2 decrypt the encryption keys using AES self encryption key?

**Comment by murali-shris** [comment]
> > Note that we store the encryption private key and the AES 'self' encryption key in 'local' storage ([at_client_mobile](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client_mobile/lib/src/at_client_service.dart#L129-L142), [at_onboarding_cli](https://github.com/atsign-foundation/at_libraries/blob/trunk/packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart#L208-L235)) and they are [never synced](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client/lib/src/util/sync_util.dart#L116-L126) to cloud secondary. For now (*), the atClient will always need to store those keys somewhere locally; an atKeys file is a reasonable choice if the client does not have 'LocalSecondary' storage.
> > (*) Once [the APKAM proposal](https://github.com/atsign-foundation/at_protocol/blob/trunk/decisions/2023-01-pkam-per-app-and-device.md) has been implemented, the encryption private key and the self encryption key will be stored on the cloud secondary, but encrypted using the client's PKAM public key. At that point, a client will only need the PKAM private key so that it can (1) sign the PKAM challenge with the PKAM private key, and (2) decrypt the encryption keys using the PKAM private key
> 
> (2) decrypt the encryption keys using AES self encryption key?

**Comment by murali-shris** [comment]
draft pull request
https://github.com/atsign-foundation/at_libraries/pull/301
Pending:
* address review comments
* testing

**Comment by gkc** [comment]
> (2) decrypt the encryption keys using AES self encryption key?

No - the whole point is to be able to store both the AES self encryption key and the encryption private key in the atServer. See the APKAM impl proposal linked above for details.

But that's in the future. Right now, we need to store those keys somewhere. Local secondary is ideal right now, but if the client doesn't use local storage, atKeys file is the fallback solution

**Comment by murali-shris** [comment]
@gkc As a part of onboarding flow, we have to read the public key from sim card and update in secondary server.
How can I plugin this logic? Through a new method in at_chops?

**Comment by gkc** [comment]
Yes that sounds sensible. Then the onboarding code can ask the atChops instance for it

**Comment by murali-shris** [comment]
Work completed in PR57
* at_chops, at_lookup and at_onboarding_cli changes for secure pkam auth.
* at_server changes merged to trunk
* manual testing with onboarding_cli pointing to DESS server complete
* pending  - PR review, at_chops/at_lookup package publishing. Addressing review comments, add test automation
PRs
Base PR - https://github.com/atsign-foundation/at_libraries/pull/301
at _chops - https://github.com/atsign-foundation/at_libraries/pull/306
at_lookup - https://github.com/atsign-foundation/at_libraries/pull/311

**Comment by murali-shris** [comment]
Work completed in PR58
* at_chops and at_lookup publishing
* manual testing with published version of at_chops and at_lookup
* added functional test to test secondary with ecc public key
* fixed issues in github actions related to functional test run
Base PR is ready for review
https://github.com/atsign-foundation/at_libraries/pull/301

**Comment by murali-shris** [comment]
at_onboarding_cli 1.2.6 published with the changes
