### ISSUE TITLE
Add more help text and clearer error messages to onboarding_cli

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_libraries#312]
### Is your feature request related to a problem? Please describe.

While using activate_cli I found myself stuck as I was not able to figure out what was wrong after getting "Error:auth failed". It took looking at server logs to see that the activation was failing due to an issue with the cram key I was using. 

### Describe the solution you'd like

It would be nice if the tool provided more specific help text are more context in the error messages in order to help people to determine why something isn't working.

**Comment by srieteja** [comment]
This is a doc listing all the exceptions that at_onboarding_cli throws 
https://docs.google.com/spreadsheets/d/1-olvPC42Ddi3YIut2J5g26TQuz257h9KYgpJ9XTnSO0/edit?usp=sharing

**Comment by srieteja** [comment]
The necessary changes have been made in the attached PR. Waiting to hear on review/feedback
