### ISSUE TITLE
Update onboarding_cli and activate_cli with new activation process of AtRegistrar

### ISSUE THREAD

**Issue by srieteja** [atsign-foundation/at_libraries#330]
### Describe the bug

The registrar no longer supports the use of qr_code to activate an atsign. But onboarding_cli currently relies completely on qr_code /cram secret to activate an atsign. At the moment this makes onboarding_cli completely unusable for activation.

### Expected behavior

OnboardingCLI should be able to activate atsigns

### Additional context

AtRegistrar has migrated to an API call and OTP based cram_secret fetching instead of the having to use a qr_code. 

### Process Checklist

- [x] Modify OnboardingCLI activation process
- [x] Consume these changes in activate_cli
- [x] Update tests to match new behaviour
- [x] Update docs/readme
- [x] Publish new version of onboarding_cli

**Comment by cconstab** [comment]
I noticed if you try to re activate you get a confusing answer. Better to alert the user that the atSign is already activated..

```
cconstab@tarial at_onboarding_cli % dart run bin/activate_cli.dart -a @blueheavybadger
[Information] Root server is root.atsign.org
[Information] Registrar url provided is my.atsign.com
[Information] Activating your atSign. This may take up to 2 minutes.
Successfully sent verification code to your registered e-mail
[Action Required] Enter your verification code: (verification code is not case-sensitive)
8xpq
[Information] CRAM Key fetched successfully
Connecting to secondary ...1/50
[Error] Activation failed. It looks like something went wrong on our side.
Please try again or contact support@atsign.com
Cause: Exception: Auth failed
cconstab@tarial at_onboarding_cli % 

```


This can be checked with an API from @athandle

**Comment by athandle** [comment]
@srieteja let me know if you need help
https://www.wavi.ng/status/atSign API with 200 status will confirm you that atSign is active

**Comment by gkc** [comment]
This is the last thing outstanding blocking the next release of sshnoports

**Comment by gkc** [comment]
@srieteja @murali-shris @VJag please prioritize this and let me know if there's any blocker

**Comment by srieteja** [comment]
No blockers @gkc, some changes broke functional tests which are being fixed as we speak.

Update: The isAtsignOnboarded() functionality that I added today is causing an issue in the tests; although it works fine in the manual testing. Fixed all the functional tests related to this except one. Trying to fix this asap so that we can publish the package.

**Comment by cconstab** [comment]
When using the lib and the atSign is already activated the app hangs and never returns a prompt..

[Information] Root server is root.atsign.org
[Information] Registrar url provided is my.atsign.com
[Information] Activating your atSign. This may take up to 2 minutes.
[Information] Successfully sent verification code to your registered e-mail
[Action Required] Enter your verification code: (verification code is not case-sensitive)
RPRB
[Information] CRAM Key fetched successfully
Connecting to secondary ...1/50
[Error] atsign is already activated




Noticed new behaviour that you need to close(0) after the lib call which was not needed in the past.. This is noted in the example code..



Thanks
