### ISSUE TITLE
How do I know if the activation was successful from a bash script ?

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_libraries#349]
### Is your feature request related to a problem? Please describe.

Would be better if package:at_onboarding_cli/src/activate_cli/activate_cli.dart returned a true/false if activation was successful.

Currently is returns a Future<void> :-(

### Describe the solution you'd like

Provide a 0 or -1 as per Unix conventions

### Describe alternatives you've considered

Cannot think of a better way

### Additional context

@XavierChanth  / @JeremyTubongbanua  you have other ideas ?

**Comment by gkc** [comment]
Has been implemented for some time.
