### ISSUE TITLE
Fix at_onboarding_cli functional tests that are being skipped right now

### ISSUE THREAD

**Issue by srieteja** [atsign-foundation/at_libraries#366]
### Is your feature request related to a problem? Please describe.

A couple of at_onboarding_cli functional tests have been skipped due to the expediated release of v1.3.0. These were were behaving in an unexpected manner and hence they were skipped. And the package was realeased after rigorous manual testing.

### Describe the solution you'd like

These tests need to be fixed and need to be enabled.

### Additional context

After some testing we have observed the error might be that activate_cli is asking for a verification code even when cram key is readily provided. Will be creating a ticket for onbaording_cli to fix this issue and these tests will be enabled after that fix has been made.

**Comment by srieteja** [comment]
The tests that deal with onboarding are currently failing because the isOnboarded() check in OnboardingService keeps returning true in the test environment which throws an exception and exits the tests.

**Comment by srieteja** [comment]
This ticket is currently waiting for APKAM to be integrated into onboarding_cli. Will merge the fix as soon as that has been completed.

**Comment by gkc** [comment]
@srieteja Is it time to look at this ticket again?

**Comment by srieteja** [comment]
yes, @gkc. I'll update the PR and follow up with murali and sita reg review.
