### ISSUE TITLE
new at_onboarding package to remove code duplication between at_client_mobile and at_onboarding_cli

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_libraries#415]
### Is your feature request related to a problem? Please describe.

Onboarding and authentication logic is duplicated between at_client_mobile and at_onboarding_cli 

### Describe the solution you'd like

move the common logic between at_client_mobile and at_onboarding_cli to a new package.
write unit/test functional tests for the common logic

**Comment by murali-shris** [comment]
APKAM changes are currently  implemented and under review/testing
https://github.com/atsign-foundation/at_libraries/tree/apkam_onboarding_changes
https://github.com/atsign-foundation/at_client_sdk/tree/apkam_onboarding_changes
Move common code from these branches to a new package - at_onboarding
Duplicate code:
1) https://github.com/atsign-foundation/at_client_sdk/blob/apkam_onboarding_changes/packages/at_client_mobile/lib/src/auth/at_auth_service_impl.dart
methods: onboard, authenticate
https://github.com/atsign-foundation/at_libraries/blob/apkam_onboarding_changes/packages/at_onboarding_cli/lib/src/onboard/at_onboarding_service_impl.dart
methods: onboard, authenticate

**Comment by murali-shris** [comment]
analysis and arch call discussion
https://docs.google.com/document/d/1n24j3f73jBdMQLAmQRGcR1iCi7LrCixVA8_mObzGn1s/edit
started with impl of at_auth package. 30% complete.

**Comment by murali-shris** [comment]
@gkc 
During initial onboard 
"client stores two keys on the server via enroll request
default self encryption key - encrypted with APKAM symmetric key
default encryption private key - encrypted with APKAM symmetric key"
I was trying to replace the call to EncryptionUtil.encryptValue(..) with at_chops.encryptString(..)
I just realised that we were not setting IV while encrypting the keys.
Should we also send the IV along with the enroll request and then subsequently store IV in metadata while saving the keys on server?

**Comment by gkc** [comment]
Ideally yes, although it is not crucial right now, since we're not currently using that symmetric key for anything else.

**Comment by murali-shris** [comment]
at_auth 1.0.0 published.
