### ISSUE TITLE
chore(at_commons): Clean Up Scope Pollution in at_constants.dart

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_libraries#417]
I wanted to point out some scope pollution in at_commons which could be a trip up for other devs in the future:

While refactoring sshnoports, the namespace variable from at_commons' constants was being used (instead of my actual namespace) I didn't know to correct it since there was another namespace in scope (I wasn't getting red squiggles so I didn't catch that something was wrong). 

For the devs that typically maintain at_commons: 

Do we need this file in scope? Can we get away with removing it from the export?
OR
Can I move these into a class as static constants so that we aren't causing so much scope pollution? 

Both of these solutions are breaking changes, but there really is no way around it if we want to undo the scope pollution.

https://github.com/atsign-foundation/at_libraries/blob/fb580b2ec152fe580ad6b7a1a7c8b8e18fbc9970/packages/at_commons/lib/src/at_constants.dart#L95

**Comment by gkc** [comment]
Resolved by https://github.com/atsign-foundation/at_libraries/pull/419 I think, right @XavierChanth ?

**Comment by xavierchanth** [comment]
yes
