### ISSUE TITLE
at_chops - upgrade dependencies and modify example

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_libraries#429]
### Describe the bug

* at_chops package has outdated dependencies
* at_chops example has deprecated methods

### Steps to reproduce

* https://pub.dev/packages/at_chops/score

### Expected behavior

* at_chops pubspec should have latest date dependencies
* at_chops example should use new methods in place of deprecated methods
* other packages using at_chops should work fine with upgraded dependencies

**Comment by srieteja** [comment]
The implementation for this is present in the linked PR. For the successful completion of this task, PR:https://github.com/atsign-foundation/at_client_sdk/pull/1150 needs to be merged. Carrying this ticket to PR74 for getting both the PRs merged and all relevant packages published.

**Comment by purnimavenkatasubbu** [comment]
Published [at_chops]( https://pub.dev/packages/at_chops/versions/1.0.7). Tested other packages and apps with at_chops.

All the test information has been updated in the [PR](https://github.com/atsign-foundation/at_libraries/pull/484)
