### ISSUE TITLE
RegexUtil.keyType can incorrectly return `reservedKey` instead of `invalidKey`

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_libraries#437]
### Describe the bug

Here's a test case which I added into at_key_regex_test.dart to illustrate the problem
```dart
    test('Validate no false positives for reserved key type', () {
      var keyTypeList = [];
      var fails = [];

      keyTypeList.add('public:publickey');
      keyTypeList.add('public:signing_publickey');

      for (var key in keyTypeList) {
        var type = RegexUtil.keyType(key, false);
        if (type != KeyType.invalidKey) {
          fails.add('got $type for $key - expected KeyType.invalidKey');
        }
      }
      expect(fails, []);
    });
  });
```

Note that while `public:publickey@alice` and `public:signing_publickey@alice` are valid reservedKeys, they are NOT valid if the `@alice` suffix is not included

### Steps to reproduce

Execute the test case above and you will see this output
```
Expected: []
  Actual: [
            'got KeyType.reservedKey for public:publickey - expected KeyType.invalidKey',
            'got KeyType.reservedKey for public:signing_publickey - expected KeyType.invalidKey'
          ]
```

### Expected behavior

The check for reserved key type needs to be tightened up - possibly by splitting into two main regex fragments - one which asserts the presence of the `@atsign` suffix where it is required, and another which asserts its NON-presence where it must NOT be present e.g. for `at_pkam_publickey`

**Comment by srieteja** [comment]
I was able to replicate the issue and come up with a fix. Carrying it forward to PR74 for implementation and testing.

**Comment by srieteja** [comment]
The implementation and most of the tests are in the attached pull request. One round of testing has been completed which identified some issues in the packages that consume this version of at_libraries. Most of these have been fixed, but one issue is yet to be fixed. Carrying it to PR75 for a fix in a consumer package and one more round of testing.
