### ISSUE TITLE
feat: at_onboarding_cli store enrollment details in local secondary after apkam auth is success

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_libraries#556]
### Is your feature request related to a problem? Please describe.

* https://github.com/atsign-foundation/at_client_sdk/issues/1269
Once this feature is merged, in order to enforce apkam authorization checks on client side, we need enrollment details on the local secondary to retrieve namespaces and access

### Describe the solution you'd like

* Store enrollment details (namespace and access) on the client side after apkam auth is success.
* Enroll details are required on local storage for at_client to perform enrollment authorization checks on local secondary verbs.

**Comment by murali-shris** [comment]
Changes in this branch
https://github.com/atsign-foundation/at_libraries/tree/save_enrollment_details_cli
There is currently an issue when enrollment details are not  in local secondary , there is an exception thrown.
have to get enrollment details using enroll:fetch.

**Comment by srieteja** [comment]
Had to put this on pause to work on the at_widgets deprecation issues. Carrying it forward to PR88 to complete the tests and get the PR reviewed/closed.
