### ISSUE TITLE
fix: auth_cli enrollment saves non-named atKeys file

### ISSUE THREAD

**Issue by Xlin123** [atsign-foundation/at_libraries#601]
### Describe the bug

~/.local/bin/at_activate enroll -a @bagel69   -s passcode-p noports   -d apaz -k ~/.atsign/keys/

[Success] Your .atKeys file saved at /home/avlazure/.atsign/keys/.atKeys

### Steps to reproduce

Go through the APKAM flow and supply -k with a directory.

### Expected behavior

generates either @bagel69_key.atKeys or something along those lines.

@gkc mentioned: 

>  I decided to make -k mandatory because of the dangers inherent in testing situations where the "original" keys are in ~/.atsign/keys and then you accidentally overwrite. I think I added protection so it'll fail if the file exists but it felt safer overall just to make the user conscious of where the keys files would go

**Comment by srieteja** [comment]
waiting for PR review. Carrying it forward to PR93

**Comment by srieteja** [comment]
Closing this as the same issue is solved in https://github.com/atsign-foundation/at_libraries/issues/629
