### ISSUE TITLE
at_activate being able to delete denied entries in `list`

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_libraries#628]
### Is your feature request related to a problem? Please describe.

I have a denied key and would like to delete it from the `list`

Currently there is no way to delete entries..

### Describe the solution you'd like

```
╰$ at_activate interactive -a @ssh_1
Connecting ... Connected
$ list
Found 1 matching enrollment records
Enrollment ID                         Status    AppName             DeviceName                            Namespaces
707a70e6-ff19-4a46-82c1-9c7cde186039  denied    sshnp               orac_ssh_1                            {sshnp: rw, sshrvd: rw}
$ delete -i 707a70e6-ff19-4a46-82c1-9c7cde186039
$ list
Found 0 matching enrollment records
Enrollment ID                         Status    AppName             DeviceName                            Namespaces

```

**Comment by srieteja** [comment]
Implementation is partially complete, carrying this forward to PR95 to complete implementation and tests.

**Comment by srieteja** [comment]
Server-side changes have been merged into the at_server codebase through [at_server changes](https://github.com/atsign-foundation/at_server/pull/2095). Once the latest version of at_server is released with these changes, the changes in at_activate (in [at_activate changes](https://github.com/atsign-foundation/at_libraries/pull/670)) can be merged.
