### ISSUE TITLE
at_activate creates atKeys files but in the wrong place. (sshnp v5.5.0 binaries)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_libraries#629]
### Describe the bug

when creating a new request for keys the keyfil is created but in a subdirectory and not in the place it should.

### Steps to reproduce

```
C
cconstab@orac:~$ at_activate enroll -s 9DWFF1  -p sshnp   -d orac_ssh_2  -n "sshnp:rw,sshrvd:rw" -a @ssh_1  --keys ~/.atsign/keys/@ssh_1_newkeys
Submitting enrollment request
Enrollment ID: 672e0d46-2e86-443e-8b79-be9d0078fca9
Waiting for approval; will check every 10 seconds
Checking ...  not approved. Will retry in 10 seconds
Checking ...  not approved. Will retry in 10 seconds
Checking ...  approved.
Creating atKeys file
[Success] Your .atKeys file saved at /home/cconstab/.atsign/keys/@ssh_1_newkeys/.atKeys
```

Note `[Success] Your .atKeys file saved at /home/cconstab/.atsign/keys/@ssh_1_newkeys/.atKeys`

This should I think read `[Success] Your .atKeys file saved at /home/cconstab/.atsign/keys/@ssh_1_newkeys.atKeys`

### Expected behavior

Keys created in the right place as requested

### Smartphones

- at_activate from v5.5.0 of sshnp

`Version : 5.5.0 (core: 6.1.0)`

**Comment by cconstab** [comment]
Does this need to be pushed to pub dev?
@sitaram-kalluri

**Comment by sitaram-kalluri** [comment]
> Does this need to be pushed to pub dev? @sitaram-kalluri

@cconstab : Yes, we need to publish at_onboarding_cli package.

**Comment by sitaram-kalluri** [comment]
Tested the changes with noports by adding dependency_overrides for at_onboarding_cli to use git trunk branch and works as expected. Attaching the test log.

```
sitaram@sitaram-ThinkPad-E14:~/IdeaProjects/atsign/noports/packages/dart/sshnoports$ ./bin/at_activate enroll -s ABC123 -p myapp -d local -n "buzz:rw" -a @sitaram -r vip.ve.atsign.zone -k ~/keys/akam_keys/@sitaram_1_newkeys
Submitting enrollment request
Enrollment ID: dcebb3a6-6a3c-42dd-bce1-27f674605a6b
Waiting for approval; will check every 10 seconds
Checking ...  not approved. Will retry in 10 seconds
Checking ...  not approved. Will retry in 10 seconds
Checking ...  approved.
Creating atKeys file
[Success] Your .atKeys file saved at /home/sitaram/keys/akam_keys/@sitaram_1_newkeys.atKeys
```

Publishing the at_onboarding_cli package with version v 1.6.2 which will have the fix.
