### ISSUE TITLE
Add Encryption Password Option to CLI Commands in `at_onboarding_cli` for Onboard/Enroll**

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_libraries#691]
### Is your feature request related to a problem? Please describe.

There is no option to supply an encryption password when using the onboard/enroll commands, which can leave sensitive data unprotected. Adding this option will improve security by allowing users to encrypt data during these processes.

### Describe the solution you'd like

Support password-protected encryption

### Additional context

Linking the main ticket [https://github.com/atsign-foundation/at_libraries/issues/604](url)

**Comment by sitaram-kalluri** [comment]
The changes are completed and pending work is up merge the changes and publish the packages.
