### ISSUE TITLE
Add Optional Encryption Password Command-Line Argument to CLIBase in at_cli_commons

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_libraries#692]
### Is your feature request related to a problem? Please describe.

Currently, there is no way to provide an encryption password directly through the command-line interface, which limits the ability to protect sensitive data. By 

### Describe the solution you'd like

Adding an optional encryption password command line argument

**Comment by purnimavenkatasubbu** [comment]
Adding the main ticket #604

**Comment by sitaram-kalluri** [comment]
The changes are published in at_cli_commons: v1.3.0. Closing this ticket here.
