### ISSUE TITLE
atsign.dev 2.0 : Script needed to import library descriptions and relevant content from github/pub.dev

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_libraries#77]
As discussed on Monday, June 21st in the Engg. stand, we dont want to duplicate information on the dev site. The best way to do it is to have one source of info either from Git or Pub.dev. We need a script that pulls the relevant info to the Dev site on a regular basis.

**Comment by cpswan** [comment]
Closed by [asign.dev#102](https://github.com/atsign-foundation/atsign.dev/pull/102)
