### ISSUE TITLE
atsign.dev 2.0 : Content changes on pub.dev for Libraries

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_libraries#78]
- [x]  Change the current @developer logo to @ dev to make it consistent across Github
- [ ]  'Now for a little internet optimism' needs to change to whatever we decide is our new tagline for messaging
- [x]  Revisit descriptions across libraries - see if it makes sense to use @protocol vs. @platform

**Comment by cpswan** [comment]
@anthonyvprakash this got buried whilst waiting for messaging to be straightened out. Are you OK to close for now, and we can have other tickets later when we decide how to use 'Flip the Internet' in dev branding?

**Comment by anthonyvprakash** [comment]
This is a duplicate ticket. Being tracked on other [tickets](https://github.com/atsign-foundation/at_client_sdk/issues/201)
