### ISSUE TITLE
Missing documentation - at_lookup (Scores Tab)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_libraries#86]
[Support multiple platforms dropdown ](https://pub.dev/packages/at_lookup/score)missing documentation for the following:

- [x] Follow dart file conventions
- [ ] Support multiple platforms
- [x] Pass static analysis

**Comment by DivyaYadavareddy** [comment]
Inorder to remove monitorclient from at_lookup, deprecated method at_client.startMonitor has to be removed completely. This will be done in a future version.

**Comment by ksanty** [comment]
Hi @kalluriramkumar we need to review this very old ticket for accuracy, potentially close it and divert to the new pub.dev publishing issue. Creating new issue cards today.
