### ISSUE TITLE
Review for missing documentation - at_server_status (API Reference)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_libraries#90]
- [ ] Right nav bar under documentation [API Reference](https://pub.dev/documentation/at_server_status/latest/) requires content review (samples and examples)
- [ ] Is [documentation link](https://atsign.dev) pointing to the correct location?

Please check libraries link as well (current, samples and examples)
[LIBRARIES](https://pub.dev/documentation/at_server_status/latest/)
- [ ] at_server_status
- [ ] at_status_impl

**Comment by cpswan** [comment]
This should be worked around by https://github.com/atsign-foundation/atsign.dev/pull/217

We need to fix pubspec.yaml and release to pub.dev for a permanent fix (and then we can remove the workaround)

**Comment by ksanty** [comment]
> This should be worked around by [atsign-foundation/atsign.dev#217](https://github.com/atsign-foundation/atsign.dev/pull/217)
> 
> We need to fix pubspec.yaml and release to pub.dev for a permanent fix (and then we can remove the workaround)

Leaving this issue opened because the API reference piece still needs to be addressed.

**Comment by ksanty** [comment]
Hi @kalluriramkumar we need to review this very old ticket for accuracy, potentially close it and divert to the new pub.dev publishing issue. Creating new issue cards today.
